[1,"Pre-pilot"],
       [11,"Are the conceptual / structural issues identified in the early questionnaire design process sufficiently explored?"],
       [11,"How might the composition of the focus (gender, age, religion, caste/socioeconomic status) affect responses?"],
       [11,"Try to get at how potential respondents think about the key indicators you are trying to measure"],
       [11,"Do you have a translator providing simultaneous translation? If not, does the amount of note-taking correspond to the amount of discussion?"],
     [1,"Survey Design"],
       [11,"Do the questions make sense to the respondent?"],
         [111,"Watch how the respondent reacts to each question – any confusion? How is the reaction time?"],
         [111,"Are there questions that require explanation by enumerator, or clarification from respondent?"],
         [111,"Follow-up with the enumerator (and possibly the respondent) on questions that seemed problematic: is the issue translation? Phrasing? Conceptual? Cultural?"],
       [11,"Are answer options comprehensive?"],
         [111,"Ensure that all ‘other’ responses are specified and recorded"],
       [11,"Is the enumerator following the scripted translations?"],
         [111,"If not, ask the enumerator to note any translation issues to discuss with the team."],
         [111,"If you do not speak the language, you can still note if interviewer’s questions were noticeably longer/shorter than the written question."],
     [1,"Interview flow and timing"],
       [11,"How is the flow of the interview?"],
         [111,"Any pauses? (likely areas where interviewers need more instructions)"],
         [111,"Are there times when the respondent looks bored? Uncomfortable? Losing interest?"],
       [11,"Could the order of modules be improved? The order of questions within modules?"],
       [11,"How long does the interview take?"],
         [111,"Check length of each module by noting start and stop time."],
         [111,"Expect that pilot interviews will take much longer than actual interviews (likely twice as long) – interviewers are expected to do extra probing, take qualitative notes, and record open-ended responses, and the survey instrument may not yet flow well"]
     ];
