[1,"Thanksgiving preperations"],
  [2,"Buy turkey"],
  [2,"Buy booze"],
    [3,"Buy beer"],
    [3,"Buy Wine"],
[1,"Survey Design"],
  [2,"Do the questions make sense to the respondent?"],
    [3,"Watch how the respondent reacts to each question – any confusion? How is the reaction time?"],
    [3,"Are there questions that require explanation by enumerator, or clarification from respondent?"],
    [3,"Follow-up with the enumerator (and possibly the respondent) on questions that seemed problematic: is the issue translation? Phrasing? Conceptual? Cultural?"],
  [2,"Are answer options comprehensive?"],
    [3,"Ensure that all ‘other’ responses are specified and recorded"],
  [2,"Is the enumerator following the scripted translations?"],
    [3,"If not, ask the enumerator to note any translation issues to discuss with the team."],
    [3,"If you do not speak the language, you can still note if interviewer’s questions were noticeably longer/shorter than the written question."],
[1,"Interview flow and timing"],
  [2,"How is the flow of the interview?"],
    [3,"Any pauses? (likely areas where interviewers need more instructions)"],
    [3,"Are there times when the respondent looks bored? Uncomfortable? Losing interest?"],
  [2,"Could the order of modules be improved? The order of questions within modules?"],
  [2,"How long does the interview take?"],
    [3,"Check length of each module by noting start and stop time."]
