[1,"De-identification"],
  [2,"Make sure all personally-identifying information (PII) is removed. If you wish to retain all variables in the survey for completeness, create de-identified versions of PII variables as described below and attach a list of all original PII variables that should not be released with your submission."],
    [3,"DROP names of survey respondents, household members, enumerators, and any other associated respondent contact information. DROP names of admnistrative units below the district level, but keep district level names in ID form (i.e. keep an encrypted, encoded version of the district IDs)."],
    [3,"ENCRYPT categorical variables by dropping the labels for encoded variables (if string, encode first). This mostly applies to names of schools, districts, and other administrative units relevant to the research question which will differ by country and by project."],
    [3,"MASK values of GPS coordinates if the GPS information is related to the research question. Otherwise, DROP GPS variables."],
  [2,"If the survey results haven't been published yet, list any variables identifying treatment assignment and flag them as embargoed on the submission form to prevent their usage before the final paper is published. "],
  [2,"Remove or embargo any sensitive PII according to survey context. Possible examples include religion and ethnicity."],
[1,"Data Cleaning"],
  [2,"Recommended: Use the JPAL/PII_Scan (https://github.com/J-PAL/stata_PII_scan) to check if all needed PII have been dropped from the data set."]
  [2,"Recommended: Install the iefieldkit package (https://dimewiki.worldbank.org/wiki/Iefieldkit) to use the iecodebook command for data cleaning purposes"],
  [2,"Does the ID variable uniquely identify observations?"],
  [2,"Is the ID the first variable listed?"],
  [2,"Does the order of the variables in the dataset match the order of the questions in the accompanying questionnaire?"],
  [2,"Are all variables labeled?"],
  [2,"Do variable labels match the labels in the accompanying questionnaire?"],
  [2,"Do all factor variables have value labels?"],
  [2,"Do all value labels match with the labels in the accompanying questionnaire?"],
  [2,"Are all missing values mentioned in the data entry dictionary (paper-based survey) or the questionnaire's choice list (computer-based survey) correctly coded and labeled?"],
  [2,"Are all missing values otherwise not mentioned in the data entry dictionary (paper-based survey) or the questionnaire's choice list (computer-based survey) correctly code and labeled?"],
  [2,"Do values in the data set match the values mentioned in the data entry dictionary (paper-based survey) or the questionnaire's choice list (computer-based survey) for each variable?"],
 [2,"Are all labels translated into English?"]
[1,"Saving the Data Set"],
  [2,"Use the cleaned data set that does not include constructed variables"],
  [2,"Compress the data set to reduce the file size"],
  [2,"Save the data set in the earliest Stata version compatible with your data formats and in a different folder than where the raw data set is present"],
[1,"Supporting Documents"],
  [2,"IE Concept Note"],
  [2,"Questionnaire"],
    [3,"The paper version of the qustionnaire is prefered to the excel-based Survey CTO form as the latter is harder to read"],
    [3,"Names of villages, schools, health facilities, etc listed as response options should be removed"],
  [2,"Enumerator manuals"],
  [2, "Field Work Details: dates on which the field work occurred, total number of households visited, refusal rates, total number of households and individuals included in the final sample, problems that occurred during the administration of the survey (strikes, inclement weather, inability to enter parts of the country)"],
  [2,"Data Cleaning Documentation:"],
    [3,"Data cleaning code files],
    [3,"Documention on changes made during the data cleaning process. E.g. how missing values were dealt with, how data set and/or survey discrepancies were dealt with, etc"],
    [3,"If variables were masked for de-identification, report method used"],
    [3,"If applicable, describe how to link observations across data files (e.g. through Master Dataset)"],
    [3,"If applicable, final codebooks created from iecodebook"],
  [2,"Data dictionary and list of datasets included, if applicable"],
  [2,"Code Review document indicating our efforts to adhere to reproducability guidelines are met."],
  [2,"Baseline report, if available"],
  [2,"Survey Methodology description"],
  [2,"Publication citation"],
[1,"Submission"],
  [2,"We recommend publishing data sets as impact evaluation surveys under licensed access"],
  [2,"Go to the MicroData Library Home Page (http://microdatalib.worldbank.org/) and log in with your UPI and passcode."],
  [2,"Click the link to “Deposit data” and next “Sign in to get started”."],
  [2,"If you are a returning user, all the projects that you have deposited will show up in the list either as “DRAFT” or “PROCESSED”. If you are a first-time user, click “Create New Project” to start with the process. Mandatory fields will be marked with stars. Provide “Title”, “Short name”, one paragraph of “Description”, and “Collaboration” which will include the email addresses of other Bank staff who may be authorized to make future edits and review this project. All the information provided here can be edited later."],
  [2,"Fill in each field as much as possible based on project information, which can be found in the concept note, baseline report, or other project documentation."],
  [2,"Load data files and other documents"],
  [2,"If required, embargo access to data until the completion of the project"]
  [2,"Review by Team Member: Send the links to the project editing page to PIs, project manager, field coordinators and other team members for review and comments before submitting the project."],
  [2,"Review by Data Group:  After submitting the project, staff from the Development Data Group will review the form and uploaded data files, confirm the successful documentation and access authority, and/or contact the project creator with further questions."]
