  [1,"Submitting Results Tables Checklist"],
   [2,"Do the number of observations make sense?"],
    [3,"Do any observation numbers change when the sample should not?"],
   [2,"Do the magnitude and sign of each coefficient/summary statistic seem reasonable?"],
      [3,"Are they interpretable?"],
   [2,"Did you delete the constant term and add the control mean (if a regression table)?"],
   [2,"Did you check for joint significance of your covariates where appropriate?"],
   [2,"Did you label the dependent variables/columns?"],
   [2,"Did you label the covariates/rows?"],
   [2,"Did you add a title?"],
   [2,"Did you add explanatory notes?"],
         [3,"Do the notes to the table clearly indicate how standard errors have been estimated, and what control variables if any have been included but not shown?"],
   [2,"Is it clear what the estimation procedure is (e.g. OLS vs. probit)?"],
   [2,"Are the column widths the right size so as not to cut off text?"],
    [3,"Are you SURE?"],
   [2,"Is the bordering consistent with your other tables?"],
   [2,"Did you turn off gridlines where appropriate?"],
   [2,"Are the numbers rounded to an appropriate level, so you don’t display too many decimal places?"]

