[1,"All stages"],
  [2,"Have you identified a sufficient number of qualified interviewers?"],
  [2,"Have you trained the interviewers on the survey instrument?"],
  [2,"Have you identified a comparable area and population for the pilot?"],
  [2,"Have you secured all approvals / letters of support needed in your context?"],
  [2,"Has someone contacted the local leaders in the pilot area to inform them of planned survey activity?"],
  [2,"Will the team be staying overnight in the pilot area? If so, do you have necessary permissions to travel (from government, World Bank, etc)?"],
  [2,"Has someone taken care of the logistics (e.g. car rentals, meals or per diem for interviewers)?"],
  [2,"Do you have a venue reserved for training the interviewers?"],
[1,"Pre-Pilot"],
  [2,"Do you have a set protocol for identifying participants in focus group discussions?"],
  [2,"Do you have a form prepared for interviewers to record qualitative observations and notes from discussion?"],
  [2,"Have you tested interviewers’ note-taking abilities during the training and provided feedback on content and handwriting?"],
  [2,"If you do not speak the local language(s), do you have a tried-and-true research assistant to accompany you to translate?"],
[1,"Content-Focused Pilot"],
  [2,"Is the questionnaire you are piloting fully translated into the local language?"],
  [2,"Is the instrument formatted for printing? Make sure there are sufficient margins on all pages for taking notes."],
  [2,"Did you print enough copies of the instrument for all interviewers and all people accompanying interviews to have a copy for each planned interview?"],
  [2,"Does the survey instrument include both the research team language and local language (where different)? If not, remember to print out copies in each language as applicable."],
  [2,"Do you have access to a printer to print revisions in real time if significant changes are needed?"],
  [2,"Have you instructed interviewers (or observers) to record the start and end time for each module?"],
[1,"Data-Focused Pilot"],
  [2,"Have you office-tested the final version of the programmed instrument for any bugs, and to ensure that all questions appear as expected and reflect the final translation?"],
  [2,"Have you set up a SurveyCTO server for the pilot? (For DIME members: Remember, no data can be uploaded to the DIME Test server.)"],
    [3,"Is the name for the pilot form on the server clearly distinguishable from the final survey?"],
    [3,"Have you assigned a form id unique to the pilot? (to avoid confusing pilot data with final data)"],
    [3,"Do all team members who need it have log-on information?"],
  [2,"Is the SurveyCTO Collect app updated to the version of SurveyCTO your server is running? (See the ‘Collect’ tab on your server for instructions.)"],
    [3,"Best to update your server and app to the latest version of SurveyCTO before starting the pilot."],
    [3,"Once you have piloted, avoid updating the app even if a new version is released, to avoid compatibility issues."],
  [2,"Are all tablets / phones running the most updated version of their operating system (OS)? (or at a minimum, are they all running exactly the same OS?)"],
  [2,"Are all tablets / phones set to the correct date and time?"],
  [2,"Is the pilot-form downloaded and ready-to-go on all tablets?"],
  [2,"Are all tablets fully charged? Do you have battery packs with you in case any batteries run out?"],
  [2,"Do you have a couple of paper copies of the survey, for observers to use, and/or as a last resort in case of unsolvable tablet problems?"],
  [2,"Have you built in time to the field plan to make any required revisions to the programming and re-download the revised forms on all tablets?"],
  [2,"Have you set up Stata do-files for importing and labeling data?"],
  [2,"Have you set up a Stata do-file for running high frequency checks?"]
