[1,"De-identification"],
  [2,"Make sure all personally-identifying information (PII) is removed! If you wish to deposit all variables in the survey for completeness, create de-identified versions of variables containing PII as described below and attach a list of all PII variables that should not be released with your submission."],
    [3,"DROP names of survey respondents, household members, enumerator, and associated contact information. DROP names of villages as well if they are characterized as personally identifiable in survey context."],
    [3,"ENCRYPT categorical variables by simply dropping the labels for encoded variables (if string, encode first). This applies to names of schools, village and possibly names of other administrative units (will differ by country and by project)."],
    [3,"MASK values of GPS coordinates if GPS information is related to the research question. Otherwise, remove GPS variables."],
  [2,"If results haven't been published yet, list any variables identifying treatment assignment and flag them as embargoed on the submission form to prevent their usage before the final paper is published. "],
  [2,"Remove or embargo any sensitive, potentially identifying information according to survey context. Possible examples include religion and ethnicity."],
[1,"Data Cleaning"],
  [2,"Recommended: Use the JPAL/PII_Scan (https://github.com/J-PAL/stata_PII_scan) as a filter to check if all pii has been dropped."]
  [2,"Recommended: Install the iefieldkit package from DIME Wiki to use the iecodebook command for data cleaning purposes"],
  [2,"Does the ID variable uniquely identify observations?"],
  [2,"Are all variables labelled?"],
  [2,"Do all factor variables have value labels?"],
  [2,"Do all value labels match with the labels mentioned in the questionnaire"],
  [2,"Are all missing values correctly coded and labelled?"],
  [2,"Did you check for missing values otherwise not mentioned in the data entry dictionary (paper-based survey) or --- (Computer-based survey)"],
  [2,"Do variable names match the accompanying questionnaire?"],
  [2,"Is the ID the first variable listed?"],
  [2,"Do the order of the variables in the dataset match the order of the questions in the survey questionnaire?"],
[1,"Saving Data Set"],
  [2,"Use the cleaned dataset that does not include constructed variables"],
  [2,"Compress the dataset to reduce file size"],
  [2,"Save in the earliest Stata version compatible with your data formats and in a different folder than where the raw dataset is present"],
[1,"Supporting Documents"],
  [2,"IE Concept Note"],
  [2,"Questionnaires"],
    [3,"Paper format equivalent is better than CTO form"],
    [3,"Names of villages, schools, health facilities, etc listed as response options should be removed"],
  [2,"Enumerator manuals"],
  [2, "Field work details: dates on which the field work occurred, total number of households visited, refusal rates, total number of households and individuals included in the final sample, problems that occurred during the administration of the survey (strikes, inclement weather, inability to enter parts of the country)"],
  [2,"Data cleaning documentation:"],
    [3,"Codes for missing values in survey and in dataset"],
    [3,"Record changes made during the data cleaning process in an easy to share manner."],
    [3,"If variables were masked for de-identification, report method used"],
    [3,"If applicable, describe how to link observations across data files (e.g. through Master Dataset)"],
  [2,"Data dictionary and list of datasets included, if applicable"],
  [2,"Code Review document indicating our efforts to adhere to reproducability guidelines are met."],
  [2,"Baseline report, if available"],
  [2,"Methodology description"],
  [2,"Publication citation"],
[1,"Submission"],
  [2,"We recommend publishing data sets as impact evaluation surveys under licensed access"],
  [2,"Go to MicroData Library Home Page (http://microdatalib.worldbank.org/) and log in with your UPI and passcode."],
  [2,"Click the link to “Deposit data” and next “Sign in to get started”."],
  [2,"If you are a returning user, all the projects that you have deposited will show up in the list either as “DRAFT” or “PROCESSED”. If you are a first-time user, click “Create New Project” to start with the process. Mandatory fields will be marked with stars. Provide “Title”, “Short name”, one paragraph of “Description” and Collaboration which will the email address of other Bank staff who may be authorized to make future edit and review this project. All the information provided here can be edited later."],
  [2,"Fill each field as much as possible based on project information, which can be found in concept note, baseline report or other project documents."],
  [2,"Load data files and other documents"],
  [2,"If required, embargo access to data until completion of the project"]
  [2,"Review by Team Member: Send the links to project editing page to PIs, project manager, field coordinators and other team members for review and comments before submitting the project."],
  [2,"Review by Data Group:  After submitting the project, staff from Development Data Group will review the form and uploaded data files, confirm the successful documentation and access authority, or contact the project creator with further questions."]
