[1,"Data Cleaning"],
  [2,"Does the ID variable uniquely identify observations?"],
  [2,"Are all variables labelled?"],
  [2,"Is any factor variable missing value labels?"],
  [2,"Are all missing values coded correctly?"],
  [2,"Do variable names match the accompanying questionnaire?"],
  [2,"Is the ID the first variable listed?"],
  [2,"Does the other variables’ order match the accompanying questionnaire?"],
[1,"De-identification"],
  [2,"Make sure all personally-identifying information (PII) is removed!"],
    [3,"DROP names of survey respondent, household members, enumerator, and associated contact information"],
    [3,"ENCRYPT categorical variables by simply dropping the labels for encoded variables (if string, encode first). This applies to names of schools, village and possibly names of other administrative units (will differ by country and by project)"],
    [3,"MASK values of GPS coordinates if GPS information is related to the research question. Otherwise, remove GPS variables"],
  [2,"Remove variables identifying treatment assignment"],
  [2,"Remove any sensitive, potentially identifying information according to survey context. Possible examples include religion and ethnicity."],
[1,"Saving Data Set"],
  [2,"Use the cleaned dataset that does not include constructed variables"],
  [2,"Use compress to reduce the file size"],
  [2,"Save in the earliest Stata version compatible with your data formats"],
[1,"Supporting Documents"],
  [2,"Questionnaires"],
    [3,"Paper format equivalent is better than CTO form"],
    [3,"Names of villages, schools, health facilities, etc listed as response options should be removed"],
  [2,"Data dictionary, if applicable"],
  [2,"Enumerator manuals"],
  [2,"IE Concept Note"],
  [2,"Baseline report, if available"],
  [2,"Methodology description"],
  [2,"Publications citation"],
  [2,"Data cleaning documentation:"],
    [3,"Codes for missing in survey and in dataset"],
    [3,"Record of any corrections made"],
    [3,"If variables were masked for de-identification, report method used"],
[1,"Submission"],
  [2,"We recommend publishing data sets as impact evaluation surveys under licensed access"],
  [2,"Go to MicroData Library Home Page (http://microdatalib.worldbank.org/) and log in with your UPI and passcode."],
  [2,"Click the link to “Deposit data” and next “Sign in to get started”."],
  [2,"If you are a returning user, all the projects that you have deposited will show up in the list either as “DRAFT” or “PROCESSED”. If you are a first-time user, click “Create New Project” to start with the process. Mandatory fields will be marked with stars. Provide “Title”, “Short name”, one paragraph of “Description” and Collaboration which will the email address of other Bank staff who may be authorized to make future edit and review this project. All the information provided here can be edited later."],
  [2,"Fill each field as much as possible based on project information, which can be found in concept note, baseline report or other project documents."],
  [2,"Load data files and other documents"],
  [2,"Review by Team Member: Send the links to project editing page to PIs, project manager, field coordinators and other team members for review and comments before submitting the project."],
  [2,"Review by Data Group:  After submitting the project, staff from Development Data Group will review the form and uploaded data files, confirm the successful documentation and access authority, or contact the project creator with further questions."]
