   [1,"Pre-pilot"],
     [2,"Are the conceptual / structural issues identified in the early questionnaire design process sufficiently explored?"],
     [2,"How might the composition of the focus (gender, age, religion, caste/socioeconomic status) affect responses?"],
     [2,"Try to get at how potential respondents think about the key indicators you are trying to measure"],
     [2,"Do you have a translator providing simultaneous translation? If not, does the amount of note-taking correspond to the amount of discussion?"],
   [1,"Survey Design"],
     [2,"Do the questions make sense to the respondent?"],
       [3,"Watch how the respondent reacts to each question – any confusion? How is the reaction time?"],
       [3,"Are there questions that require explanation by enumerator, or clarification from respondent?"],
       [3,"Follow-up with the enumerator (and possibly the respondent) on questions that seemed problematic: is the issue translation? Phrasing? Conceptual? Cultural?"],
     [2,"Are answer options comprehensive?"],
       [3,"Ensure that all ‘other’ responses are specified and recorded"],
     [2,"Is the enumerator following the scripted translations?"],
       [3,"If not, ask the enumerator to note any translation issues to discuss with the team."],
       [3,"If you do not speak the language, you can still note if interviewer’s questions were noticeably longer/shorter than the written question."],
   [1,"Interview flow and timing"],
     [2,"How is the flow of the interview?"],
       [3,"Any pauses? (likely areas where interviewers need more instructions)"],
       [3,"Are there times when the respondent looks bored? Uncomfortable? Losing interest?"],
     [2,"Could the order of modules be improved? The order of questions within modules?"],
     [2,"How long does the interview take?"],
       [3,"Check length of each module by noting start and stop time."],
       [3,"Expect that pilot interviews will take much longer than actual interviews (likely twice as long) – interviewers are expected to do extra probing, take qualitative notes, and record open-ended responses, and the survey instrument may not yet flow well"]
